# Welcome to Jekyll!

# Website settings
plugins:
  - jekyll-feed
title: Sandeep Dasari
description: Portfolio and Project Blog
keywords: blog, audio, github, programming, music, technology, machine learning, artificial intelligence, web development
baseurl: / # if you have suburl as homepage like '/homepage', please change it to '/homepage' and your repo's name should be 'homepage'
url: # url should be 'http://<github_username>.github.io/homepage' as before
# url: http://127.0.0.1:4000
img_path: '/audioblog-/static/assets/img/blog'

# author -- index page "about me" section
author:   # change following line to your infomation.
  name: Sandeep  # Be used at blog posts' author.
  first_name: Sandeep  # Be used at index page about me section.
  last_name: Dasari  # Be used at index page about me section.
  avatar: /static/assets/img/landing/avatar.png  # upload your avatar at directory and edit it.
  github_username: sandcobainer  # Leave blank if you don't have now
  linkedin_id: sandeepdasari # Leave blank if you don't have now
  facebook_username: sandcobainer # Leave blank if you don't have now
  email: sdasari38@gatech.edu  # Leave blank if you don't have now
  cv: https://sandcobainer.github.io/online-cv/ # An online CV can be printed as PDF, leave blank if you don't have now
  # skill icons are on avatar's left and right side. Reference urls are http://fontawesome.io/ and http://fizzed.com/oss/font-mfizz
  skill_icon1:
    - name: icon-cplusplus
    - name: icon-python
  skill_icon2:
    - name: icon-mongodb
    - name: icon-javascript-alt

  desc: Music technology researcher, ML engineer, audio programmer and musician (duh).
  detail: I study music technology and apply computer science into audio, digital signal processing, embedded systems and human-computer interaction devices. 
  detail:  Audio web and plugin development, VR, Audio spatialization, Data sonofication, visualization, HCI, Interactive Education, Entrepreneurship
  subtit: Can computers help us express ourselves artistically?  # Describe yourself.


# analytics
## google analytics
ga:  # if you wanna this feature, go to https://www.google.com/analytics/ to get your configuration; if not, comment following line.
  id: UA-93473370-3

## google optimize
go:
  # id:

## growingIO
gio:  # if you wanna this feature, go to https://www.growingio.com/ to get your configuration; if not, comment following line.
  # id:

## donation
donation: off  # type 'on'/'off' to choice display donation button at post page or not

## carousels
index_carousel: on  # index page carousel switch
blog_carousel: on  # blog page carousel switch

# scss
sass:
  style: compressed

# Build settings
encoding: utf-8

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
